### PR TITLE
fix: finish new replica func

### LINKED ISSUE #237: 可以吧Replica的new方法实现下。
可以吧Replica的new方法实现下。

_Originally posted by @liubaohai in https://github.com/openacid/celeritasdb/pull/234_

### PR DESCRIPTION
**Pull request by liubaohai**
# Description           

Fixes #237 

formed a **self-review** of my own code
- [ ] **Comment**:     I have **commented my code**, particularly in hard-to-understand areas
- [ ] **Doc**:         I have made corresponding changes to the **documentation**
- [x] **No-warnings**: My changes generate **no new warnings**
- [x] **Add-test**:    I have added **tests** that prove my fix is effective or that my feature works
- [x] **Pass**:        New and existing **unit tests pass** locally with my changes

### CODE REVIEW

File: components/epaxos/src/conf/conf.rs [hunk 1]
```diff
@@ -120,6 +120,17 @@ impl ClusterInfo {
...
+    /// get_group returns the GroupInfo where the specified replica in.
+    pub fn get_group(&self, rid: ReplicaID) -> Option<&GroupInfo> {
+        for group in self.groups.iter() {
+            if group.replicas.contains_key(&rid) {
+                return Some(group);
+            }
+        }
+
+        None
+    }
```
Comment (drmingdrmer) [inline components/epaxos/src/conf/conf.rs:132]: ClusterInfo.replicas.get(rid) 是个ReplicaInfo,里面有对应的group的index.

Comment (liubaohai) [reply components/epaxos/src/conf/conf.rs:132]: 嗯嗯
